config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :reply_from,
   optional: true,
   class_name: 'Comment',
   foreign_key: :reply_id

  has_many :replies, class_name: 'Comment', foreign_key: :reply_id
  has_many :likes, as: :object

  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  enum status: [ :accepted, :rejected, :unfriended ]

  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: :friend_id

  def self.still_friends?(user, friend)
    where(user_id: user.id, friend_id: friend.id).last.accepted?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  enum reaction_type: [ :like, :dislike, :laugh ]

  belongs_to :object, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes, as: :object
  belongs_to :user

  validates :content, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  enum gender: [ :male, :female, :other ]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friendships, -> { where status: 'accepted' }
  has_many :inverse_friendships, -> { where status: 'accepted' },
   class_name: 'Friendship', foreign_key: :friend_id


  validates :email, presence: true, length: { maximum: 255 }
  validates :first_name, :last_name, :username, :gender, :birthday,
    presence: true

  def friends
    friends_array = friendships.map do |friendship|
      friend = friendship.friend
      friend if Friendship.still_friends?(self, friend)
    end
    inverse_friends_array = inverse_friendships.map do  |friendship|
      friend = friendship.user
      friend if Friendship.still_friends?(friend, self)
    end
    (friends_array + inverse_friends_array).compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to image_tag("logo.png", id: "logo"), root_path, class: "navbar-brand" %>
  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to user_path(id: current_user.id), class: "nav-link user-header" do %>
            <%= image_tag user_avatar(current_user, 25), class:"rounded-circle" %>
            <span class= "">
              <% if current_user.username.nil? %>
                <%= current_user.full_name %>
              <% else %>
                <%= current_user.username %>
              <% end %>
            </span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Connect", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="icon">
              <% pending_list = current_user.pending(current_user) %>
              <i class="fas fa-bell"><%= pending_list.count %></i>
            </span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% pending_list.each do |user|%>
              <div class="navbar-item border">
                <%= link_to "#{user.full_name}", user_path(id: user.id) %>
                <%= link_to 'Confirm', accept_user_friendships_path(user_id: user.id), method: :post, class:'button is-small has-background-info' %>
                <%= link_to 'Delete', reject_user_friendships_path(user_id: user.id), method: :post, class:'button is-small' %>
              </div>
            <% end %>
          </div>
        </li>
        <!-- second nav -->
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="icon">
              <i class="fas fa-sort-down"></i>
            </span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="navbar-item border">
              <%= link_to "Edit", edit_user_registration_path(current_user), class: "" %>
            </div>
            <div class="navbar-item border">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "" %>
            </div>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class = "has-background-grey-lighter">
  <head>
    <title>Friendly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </head>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">

  <body class ="bg-deamlight">
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="top-space">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_commentform.html.erb
<% simple_form_for( new_post_comment_path( post ) ) do |comment| %>
  <%= comment.error_notification %>
  <div class='field'>
    <div class='control'>
      <%= comment.input :content, label: 'Create Comment', input_html: { class: "textarea "},
                  wrapper: false, label_html: {class: 'label'},
                  placeholder: "What is on your mind, #{current_user.username}",
                  autofocus: true %>
    </div>
  </div>
  <%= comment.button :submit, class: 'button is-info is-pulled-right' %>
  <br>
  <br>
<% end %>